version: "3.9"

services:
  smoking-tires-api:
    image: <your-dockerhub-username>/smokingtires-api:1.0
    environment:
      - DB_URL=jdbc:mysql://<your-rds-endpoint>:3306/smokingtires_prod
      - DB_USERNAME=admin
      - DB_PASSWORD=<your-rds-password>
    ports:
      - 8080:8080